import { Proyek, User, AuditLog } from '@/types'

export const DUMMY_USERS: User[] = [
  {
    id: 'u1',
    name: 'Ir. Ahmad Fauzi, MT',
    email: 'ppk@dumai.go.id',
    role: 'ppk',
    nip: '197605152003121005',
    jabatan: 'Pejabat Pembuat Komitmen',
  },
  {
    id: 'u2',
    name: 'Drs. Bambang Susilo',
    email: 'pimpinan@dumai.go.id',
    role: 'pimpinan',
    nip: '196809201995031002',
    jabatan: 'Kepala Dinas PU',
  },
  {
    id: 'u3',
    name: 'Siti Rahmawati, ST',
    email: 'pptk1@dumai.go.id',
    role: 'pptk',
    nip: '198803042012122001',
    jabatan: 'PPTK Drainase',
  },
  {
    id: 'u4',
    name: 'Rudi Hartono, ST',
    email: 'pptk2@dumai.go.id',
    role: 'pptk',
    nip: '199001152015031003',
    jabatan: 'PPTK Jalan',
  },
  {
    id: 'u5',
    name: 'Tim Perencanaan A',
    email: 'perencanaan@dumai.go.id',
    role: 'tim_perencanaan',
    nip: '199205062017041002',
    jabatan: 'Staf Perencanaan',
  },
  {
    id: 'u6',
    name: 'Tim Pengawasan B',
    email: 'pengawasan@dumai.go.id',
    role: 'tim_pengawasan',
    nip: '199108152018022001',
    jabatan: 'Pengawas Lapangan',
  },
  {
    id: 'u7',
    name: 'CV. Konsultan Mitra Riau',
    email: 'konsultan.perencana@mitra.com',
    role: 'konsultan_perencana',
    jabatan: 'Konsultan Perencana',
  },
  {
    id: 'u8',
    name: 'PT. Pengawas Prima',
    email: 'konsultan.pengawasan@prima.com',
    role: 'konsultan_pengawasan',
    jabatan: 'Konsultan Pengawasan',
  },
  {
    id: 'u9',
    name: 'Admin Sistem',
    email: 'admin@dumai.go.id',
    role: 'admin',
    jabatan: 'Administrator',
  },
]

export const USER_CREDENTIALS: Record<string, { password: string; userId: string }> = {
  'admin@dumai.go.id': { password: 'admin123', userId: 'u9' },
  'ppk@dumai.go.id': { password: 'ppk123', userId: 'u1' },
  'pimpinan@dumai.go.id': { password: 'pimpinan123', userId: 'u2' },
  'pptk1@dumai.go.id': { password: 'pptk123', userId: 'u3' },
  'pptk2@dumai.go.id': { password: 'pptk123', userId: 'u4' },
  'perencanaan@dumai.go.id': { password: 'plan123', userId: 'u5' },
  'pengawasan@dumai.go.id': { password: 'watch123', userId: 'u6' },
  'konsultan.perencana@mitra.com': { password: 'konsultan123', userId: 'u7' },
  'konsultan.pengawasan@prima.com': { password: 'konsultan123', userId: 'u8' },
}

const makeSurvey = (
  proyekId: string,
  index: number,
  koordinat: { lat: number; lng: number },
  status: 'draft' | 'submitted' | 'approved' | 'rejected',
  kondisiEksisting: string,
  permasalahan: string,
  rekomendasi = 'Tindak lanjuti melalui paket pekerjaan SDA sesuai prioritas teknis lapangan.',
) => ({
  id: `s-${proyekId}`,
  proyekId,
  tanggal: `2026-0${(index % 4) + 1}-${String(10 + index).padStart(2, '0')}`,
  userId: 'u5',
  userName: 'Tim Perencanaan A',
  koordinat,
  kondisiEksisting,
  dimensi: { panjang: 120 + index * 35, lebar: 1.2 + (index % 3) * 0.4, tinggi: 0.9 + (index % 2) * 0.3 },
  material: index % 2 === 0 ? 'Beton bertulang dan pasangan batu kali' : 'Normalisasi tanah, turap ringan, dan beton pracetak',
  permasalahan,
  rekomendasi,
  foto: [
    { id: `f-${proyekId}-1`, url: `/uploads/${proyekId}-survey-1.jpg`, uploadedAt: '2026-04-12T09:00:00', uploadedBy: 'Tim Perencanaan A', keterangan: 'Kondisi eksisting lokasi' },
    { id: `f-${proyekId}-2`, url: `/uploads/${proyekId}-survey-2.jpg`, uploadedAt: '2026-04-12T09:20:00', uploadedBy: 'Tim Perencanaan A', keterangan: 'Titik kendala lapangan' },
  ],
  status,
  createdAt: `2026-04-${String(10 + index).padStart(2, '0')}T09:00:00`,
})

const makeRab = (proyekId: string, totalAnggaran: number, status: 'draft' | 'submitted' | 'approved' | 'rejected') => ({
  id: `rab-${proyekId}`,
  proyekId,
  versi: 'v1',
  versionNumber: 1,
  items: [
    { no: '1', uraian: 'Pekerjaan Persiapan dan Mobilisasi', satuan: 'Ls', volume: 1, hargaSatuan: Math.round(totalAnggaran * 0.08), total: Math.round(totalAnggaran * 0.08) },
    { no: '2', uraian: 'Pekerjaan Utama SDA', satuan: 'Ls', volume: 1, hargaSatuan: Math.round(totalAnggaran * 0.72), total: Math.round(totalAnggaran * 0.72) },
    { no: '3', uraian: 'Pekerjaan Akhir dan Pembersihan', satuan: 'Ls', volume: 1, hargaSatuan: Math.round(totalAnggaran * 0.20), total: Math.round(totalAnggaran * 0.20) },
  ],
  totalAnggaran,
  uploadedBy: status === 'draft' ? 'Siti Rahmawati, ST' : 'CV. Konsultan Mitra Riau',
  uploadedAt: '2026-04-18T10:00:00',
  status,
  catatan: status === 'rejected' ? 'Perlu revisi volume dan analisa harga satuan.' : undefined,
})

const makeReport = (
  proyekId: string,
  koordinat: { lat: number; lng: number },
  progressFisik: number,
  disetujui: boolean,
  uraianPekerjaan: string,
) => ({
  id: `lh-${proyekId}`,
  proyekId,
  tanggal: '2026-05-20',
  userId: 'u3',
  userName: 'Siti Rahmawati, ST',
  uraianPekerjaan,
  progressFisik,
  progressKumulatif: progressFisik,
  cuaca: 'berawan',
  koordinat,
  foto: [
    { id: `fl-${proyekId}-1`, url: `/uploads/${proyekId}-laporan-1.jpg`, uploadedAt: '2026-05-20T08:00:00', uploadedBy: 'Siti Rahmawati, ST', keterangan: 'Dokumentasi progres lapangan' },
  ],
  disetujui,
  disetujuiOleh: disetujui ? 'Ir. Ahmad Fauzi, MT' : undefined,
  createdAt: '2026-05-20T08:30:00',
})

const makeIssue = (
  proyekId: string,
  index: number,
  prioritas: 'rendah' | 'sedang' | 'tinggi' | 'kritis',
  status: 'open' | 'in_progress' | 'resolved' | 'closed',
  judul: string,
  deskripsi: string,
) => ({
  id: `m-${proyekId}`,
  proyekId,
  judul,
  deskripsi,
  status,
  prioritas,
  dilaporkanOleh: 'u6',
  dilaporkanOlehName: 'Tim Pengawasan B',
  tanggal: `2026-05-${String(5 + index).padStart(2, '0')}`,
  foto: [],
  solusi: status === 'resolved' || status === 'closed' ? 'Sudah ditindaklanjuti oleh pelaksana lapangan.' : undefined,
  resolvedAt: status === 'resolved' || status === 'closed' ? '2026-05-22T10:00:00' : undefined,
  createdAt: `2026-05-${String(5 + index).padStart(2, '0')}T10:00:00`,
})

const ADDITIONAL_SDA_PACKAGES: Proyek[] = [
  {
    id: 'sda-001',
    kode: 'SDA-DRN-007/2026',
    nama: 'Rehabilitasi Drainase Jalan Ombak Dumai Barat',
    lokasi: 'Jl. Ombak, Kel. Pangkalan Sesai',
    kecamatan: 'Dumai Barat',
    koordinat: { lat: 1.6719, lng: 101.4262 },
    anggaran: 1_950_000_000,
    nilaiKontrak: 1_890_000_000,
    status: 'pelaksanaan',
    kategoriPekerjaan: 'lelang',
    jenisProyek: 'fisik',
    tahunAnggaran: 2026,
    program: 'Pengelolaan Sumber Daya Air',
    kegiatan: 'Pengelolaan dan Pengembangan Sistem Drainase',
    subKegiatan: 'Rehabilitasi Drainase Perkotaan',
    health: 'on_track',
    progressFisik: 72,
    progressKeuangan: 66,
    deviasi: 6,
    tanggalMulai: '2026-02-05',
    tanggalSelesai: '2026-07-20',
    kontraktor: 'CV. Tirta Dumai Mandiri',
    konsultanPengawasan: 'PT. Pengawas Prima',
    pptk: 'Siti Rahmawati, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [makeSurvey('sda-001', 1, { lat: 1.6719, lng: 101.4262 }, 'approved', 'Saluran tepi jalan mengalami sedimentasi sedang dan dinding pasangan lama mulai retak.', 'Genangan terjadi 20-30 cm saat hujan lebat dan mengganggu akses permukiman.')],
    rabList: [makeRab('sda-001', 1_890_000_000, 'approved')],
    laporanHarian: [makeReport('sda-001', { lat: 1.6719, lng: 101.4262 }, 72, true, 'Pemasangan pasangan batu dan pembersihan sedimen STA 0+240 s/d 0+310.')],
    catatanPengawasan: [],
    masalah: [],
    chat: [],
    assignedUsers: ['u1', 'u3', 'u6', 'u8'],
    createdAt: '2026-01-22T08:00:00',
    updatedAt: '2026-05-22T16:00:00',
  },
  {
    id: 'sda-002',
    kode: 'SDA-DRN-008/2026',
    nama: 'Normalisasi Parit Jalan Paus Kelurahan Laksamana',
    lokasi: 'Jl. Paus, Kel. Laksamana',
    kecamatan: 'Dumai Kota',
    koordinat: { lat: 1.6878, lng: 101.4439 },
    anggaran: 860_000_000,
    nilaiKontrak: 835_000_000,
    status: 'pelaksanaan',
    kategoriPekerjaan: 'rutin',
    jenisProyek: 'fisik',
    tahunAnggaran: 2026,
    program: 'Pengelolaan Sumber Daya Air',
    kegiatan: 'Operasi dan Pemeliharaan Drainase',
    subKegiatan: 'Normalisasi Saluran Rutin',
    health: 'warning',
    progressFisik: 38,
    progressKeuangan: 51,
    deviasi: -13,
    tanggalMulai: '2026-03-01',
    tanggalSelesai: '2026-06-15',
    kontraktor: 'CV. Pesisir Jaya',
    pptk: 'Siti Rahmawati, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [makeSurvey('sda-002', 2, { lat: 1.6878, lng: 101.4439 }, 'submitted', 'Parit dipenuhi sampah rumah tangga dan sedimen lunak.', 'Aliran tersumbat di depan kawasan padat penduduk.')],
    rabList: [makeRab('sda-002', 835_000_000, 'submitted')],
    laporanHarian: [makeReport('sda-002', { lat: 1.6878, lng: 101.4439 }, 38, false, 'Pembersihan manual dan pengangkutan sedimen masih berlangsung.')],
    catatanPengawasan: [],
    masalah: [makeIssue('sda-002', 2, 'tinggi', 'open', 'Akses alat berat terbatas', 'Lebar jalan lingkungan tidak memungkinkan excavator masuk penuh sehingga produktivitas rendah.')],
    chat: [],
    assignedUsers: ['u1', 'u3', 'u6'],
    createdAt: '2026-02-18T08:00:00',
    updatedAt: '2026-05-21T15:00:00',
  },
  {
    id: 'sda-003',
    kode: 'SDA-DRN-009/2026',
    nama: 'Pembangunan Box Culvert Jalan Janur Kuning',
    lokasi: 'Jl. Janur Kuning, Kel. Jaya Mukti',
    kecamatan: 'Dumai Timur',
    koordinat: { lat: 1.6964, lng: 101.4641 },
    anggaran: 2_420_000_000,
    nilaiKontrak: 2_350_000_000,
    status: 'pelaksanaan',
    kategoriPekerjaan: 'pl',
    jenisProyek: 'fisik',
    tahunAnggaran: 2026,
    program: 'Pengelolaan Sumber Daya Air',
    kegiatan: 'Pengendalian Banjir dan Genangan',
    subKegiatan: 'Pembangunan Bangunan Pelintas Air',
    health: 'kritis',
    progressFisik: 18,
    progressKeuangan: 36,
    deviasi: -18,
    tanggalMulai: '2026-02-12',
    tanggalSelesai: '2026-08-30',
    kontraktor: 'CV. Riau Beton Perkasa',
    konsultanPengawasan: 'PT. Pengawas Prima',
    pptk: 'Siti Rahmawati, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [makeSurvey('sda-003', 3, { lat: 1.6964, lng: 101.4641 }, 'approved', 'Gorong-gorong eksisting kecil dan sering tertutup sedimen.', 'Banjir mengarah ke permukiman ketika pasang laut bersamaan hujan intensitas tinggi.')],
    rabList: [makeRab('sda-003', 2_350_000_000, 'approved')],
    laporanHarian: [makeReport('sda-003', { lat: 1.6964, lng: 101.4641 }, 18, false, 'Pekerjaan galian tertunda karena muka air tinggi dan perlu pompa tambahan.')],
    catatanPengawasan: [],
    masalah: [makeIssue('sda-003', 3, 'kritis', 'in_progress', 'Dewatering belum memadai', 'Air masuk ke area galian setiap pasang sehingga pekerjaan struktur tertahan.')],
    chat: [],
    assignedUsers: ['u1', 'u3', 'u6', 'u8'],
    createdAt: '2026-01-28T08:00:00',
    updatedAt: '2026-05-22T11:00:00',
  },
  {
    id: 'sda-004',
    kode: 'SDA-DRN-010/2026',
    nama: 'Peningkatan Saluran Jalan Budi Kemuliaan',
    lokasi: 'Jl. Budi Kemuliaan, Kel. Dumai Kota',
    kecamatan: 'Dumai Kota',
    koordinat: { lat: 1.6824, lng: 101.4481 },
    anggaran: 1_270_000_000,
    nilaiKontrak: 1_225_000_000,
    status: 'selesai',
    kategoriPekerjaan: 'pl',
    jenisProyek: 'fisik',
    tahunAnggaran: 2026,
    program: 'Pengelolaan Sumber Daya Air',
    kegiatan: 'Pengelolaan Drainase Lingkungan',
    subKegiatan: 'Peningkatan Saluran Lingkungan',
    health: 'on_track',
    progressFisik: 100,
    progressKeuangan: 96,
    deviasi: 4,
    tanggalMulai: '2026-01-10',
    tanggalSelesai: '2026-04-30',
    kontraktor: 'CV. Dumai Konstruksi',
    pptk: 'Siti Rahmawati, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [makeSurvey('sda-004', 4, { lat: 1.6824, lng: 101.4481 }, 'approved', 'Saluran lama dangkal dan rusak ringan di beberapa segmen.', 'Genangan lokal terjadi di depan fasilitas umum.')],
    rabList: [makeRab('sda-004', 1_225_000_000, 'approved')],
    laporanHarian: [makeReport('sda-004', { lat: 1.6824, lng: 101.4481 }, 100, true, 'Pekerjaan selesai, pembersihan akhir dan opname lapangan sudah dilakukan.')],
    catatanPengawasan: [],
    masalah: [makeIssue('sda-004', 4, 'rendah', 'closed', 'Pembersihan akhir terlambat', 'Sisa material sempat menutup akses warga dan sudah dibersihkan.')],
    chat: [],
    assignedUsers: ['u1', 'u3', 'u6'],
    createdAt: '2026-01-05T08:00:00',
    updatedAt: '2026-05-05T12:00:00',
  },
  {
    id: 'sda-005',
    kode: 'SDA-OPR-011/2026',
    nama: 'Pemeliharaan Pintu Air Purnama',
    lokasi: 'Kawasan Pintu Air Purnama, Kel. Purnama',
    kecamatan: 'Dumai Barat',
    koordinat: { lat: 1.6627, lng: 101.4028 },
    anggaran: 640_000_000,
    nilaiKontrak: 615_000_000,
    status: 'monitoring',
    kategoriPekerjaan: 'rutin',
    jenisProyek: 'fisik',
    tahunAnggaran: 2026,
    program: 'Pengelolaan Sumber Daya Air',
    kegiatan: 'Operasi dan Pemeliharaan Infrastruktur SDA',
    subKegiatan: 'Pemeliharaan Pintu Air',
    health: 'on_track',
    progressFisik: 61,
    progressKeuangan: 59,
    deviasi: 2,
    tanggalMulai: '2026-03-10',
    tanggalSelesai: '2026-07-10',
    kontraktor: 'CV. Mekar Teknik',
    pptk: 'Siti Rahmawati, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [makeSurvey('sda-005', 5, { lat: 1.6627, lng: 101.4028 }, 'approved', 'Daun pintu air berkarat dan sistem engkol perlu perawatan.', 'Risiko lambat operasi saat hujan bersamaan pasang laut.')],
    rabList: [makeRab('sda-005', 615_000_000, 'approved')],
    laporanHarian: [makeReport('sda-005', { lat: 1.6627, lng: 101.4028 }, 61, true, 'Pelumasan mekanisme pintu air dan pengecatan primer selesai.')],
    catatanPengawasan: [],
    masalah: [],
    chat: [],
    assignedUsers: ['u1', 'u3', 'u6'],
    createdAt: '2026-02-25T08:00:00',
    updatedAt: '2026-05-22T14:00:00',
  },
  {
    id: 'sda-006',
    kode: 'SDA-DRN-012/2026',
    nama: 'Rehabilitasi Drainase Jalan Merdeka Baru',
    lokasi: 'Jl. Merdeka Baru, Kel. Teluk Binjai',
    kecamatan: 'Dumai Timur',
    koordinat: { lat: 1.6816, lng: 101.4752 },
    anggaran: 1_540_000_000,
    nilaiKontrak: 1_498_000_000,
    status: 'belum_survey',
    kategoriPekerjaan: 'lelang',
    jenisProyek: 'fisik',
    tahunAnggaran: 2026,
    program: 'Pengelolaan Sumber Daya Air',
    kegiatan: 'Pengelolaan Drainase Perkotaan',
    subKegiatan: 'Rehabilitasi Drainase Perkotaan',
    health: 'warning',
    progressFisik: 0,
    progressKeuangan: 0,
    deviasi: 0,
    tanggalMulai: '2026-06-01',
    tanggalSelesai: '2026-10-30',
    kontraktor: 'PT. Dumai Infrastruktur',
    pptk: 'Siti Rahmawati, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [],
    rabList: [makeRab('sda-006', 1_498_000_000, 'draft')],
    laporanHarian: [],
    catatanPengawasan: [],
    masalah: [],
    chat: [],
    assignedUsers: ['u1', 'u3'],
    createdAt: '2026-05-10T08:00:00',
    updatedAt: '2026-05-18T08:00:00',
  },
  {
    id: 'sda-007',
    kode: 'SDA-SRV-013/2026',
    nama: 'Survey Investigasi Genangan Bukit Datuk',
    lokasi: 'Lingkungan Bukit Datuk, Kel. Bukit Datuk',
    kecamatan: 'Dumai Selatan',
    koordinat: { lat: 1.6412, lng: 101.4514 },
    anggaran: 420_000_000,
    nilaiKontrak: 405_000_000,
    status: 'survey',
    kategoriPekerjaan: 'rutin',
    jenisProyek: 'konsultan_perencanaan',
    tahunAnggaran: 2026,
    program: 'Pengelolaan Sumber Daya Air',
    kegiatan: 'Survey dan Investigasi SDA',
    subKegiatan: 'Survey Genangan dan Drainase',
    health: 'warning',
    progressFisik: 12,
    progressKeuangan: 5,
    deviasi: 7,
    tanggalMulai: '2026-05-01',
    tanggalSelesai: '2026-06-30',
    kontraktor: 'CV. Konsultan Mitra Riau',
    konsultanPerencana: 'CV. Konsultan Mitra Riau',
    pptk: 'Siti Rahmawati, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [makeSurvey('sda-007', 7, { lat: 1.6412, lng: 101.4514 }, 'draft', 'Data genangan awal dari warga belum lengkap.', 'Perlu survey elevasi dan arah aliran sebelum rekomendasi teknis.')],
    rabList: [makeRab('sda-007', 405_000_000, 'submitted')],
    laporanHarian: [],
    catatanPengawasan: [],
    masalah: [makeIssue('sda-007', 7, 'sedang', 'open', 'Data elevasi belum lengkap', 'Tim survey perlu melengkapi titik ukur dan foto koordinat.')],
    chat: [],
    assignedUsers: ['u1', 'u3', 'u5'],
    createdAt: '2026-04-22T08:00:00',
    updatedAt: '2026-05-16T08:00:00',
  },
  {
    id: 'sda-008',
    kode: 'SDA-DRN-014/2026',
    nama: 'Penanganan Genangan Jalan Arifin Ahmad',
    lokasi: 'Jl. Arifin Ahmad, Kel. Bukit Nenas',
    kecamatan: 'Bukit Kapur',
    koordinat: { lat: 1.6156, lng: 101.3789 },
    anggaran: 2_180_000_000,
    nilaiKontrak: 2_090_000_000,
    status: 'pelaksanaan',
    kategoriPekerjaan: 'lelang',
    jenisProyek: 'fisik',
    tahunAnggaran: 2026,
    program: 'Pengelolaan Sumber Daya Air',
    kegiatan: 'Pengendalian Banjir dan Genangan',
    subKegiatan: 'Penanganan Titik Genangan',
    health: 'kritis',
    progressFisik: 24,
    progressKeuangan: 48,
    deviasi: -24,
    tanggalMulai: '2026-02-20',
    tanggalSelesai: '2026-09-10',
    kontraktor: 'PT. Cipta Drainase Riau',
    konsultanPengawasan: 'PT. Pengawas Prima',
    pptk: 'Rudi Hartono, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [makeSurvey('sda-008', 8, { lat: 1.6156, lng: 101.3789 }, 'approved', 'Saluran outlet ke parit utama lebih tinggi dari saluran lingkungan.', 'Genangan menetap lebih dari 6 jam setelah hujan lebat.')],
    rabList: [makeRab('sda-008', 2_090_000_000, 'approved')],
    laporanHarian: [makeReport('sda-008', { lat: 1.6156, lng: 101.3789 }, 24, false, 'Pekerjaan crossing saluran tertahan relokasi utilitas.')],
    catatanPengawasan: [],
    masalah: [makeIssue('sda-008', 8, 'kritis', 'open', 'Relokasi utilitas belum selesai', 'Pipa utilitas melintang pada area pekerjaan crossing dan menghambat pemasangan box.')],
    chat: [],
    assignedUsers: ['u1', 'u4', 'u6', 'u8'],
    createdAt: '2026-02-01T08:00:00',
    updatedAt: '2026-05-23T09:00:00',
  },
  {
    id: 'sda-009',
    kode: 'SDA-DRN-015/2026',
    nama: 'Peningkatan Drainase Jalan Kelakap Tujuh',
    lokasi: 'Jl. Kelakap Tujuh, Kel. Ratu Sima',
    kecamatan: 'Dumai Selatan',
    koordinat: { lat: 1.6537, lng: 101.4386 },
    anggaran: 1_760_000_000,
    nilaiKontrak: 1_710_000_000,
    status: 'pelaksanaan',
    kategoriPekerjaan: 'pl',
    jenisProyek: 'fisik',
    tahunAnggaran: 2026,
    program: 'Pengelolaan Sumber Daya Air',
    kegiatan: 'Pengelolaan Drainase Lingkungan',
    subKegiatan: 'Peningkatan Saluran Lingkungan',
    health: 'on_track',
    progressFisik: 55,
    progressKeuangan: 43,
    deviasi: 12,
    tanggalMulai: '2026-03-05',
    tanggalSelesai: '2026-08-15',
    kontraktor: 'CV. Lancang Kuning',
    pptk: 'Siti Rahmawati, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [makeSurvey('sda-009', 9, { lat: 1.6537, lng: 101.4386 }, 'approved', 'Saluran tanah perlu ditingkatkan menjadi pasangan permanen.', 'Tebing saluran mudah longsor dan menyebabkan pendangkalan.')],
    rabList: [makeRab('sda-009', 1_710_000_000, 'approved')],
    laporanHarian: [makeReport('sda-009', { lat: 1.6537, lng: 101.4386 }, 55, true, 'Pemasangan dinding saluran sisi kanan selesai 180 meter.')],
    catatanPengawasan: [],
    masalah: [],
    chat: [],
    assignedUsers: ['u1', 'u3', 'u6'],
    createdAt: '2026-02-24T08:00:00',
    updatedAt: '2026-05-20T16:00:00',
  },
  {
    id: 'sda-010',
    kode: 'SDA-DRN-016/2026',
    nama: 'Normalisasi Saluran Kampung Baru Medang Kampai',
    lokasi: 'Kampung Baru, Kel. Pelintung',
    kecamatan: 'Medang Kampai',
    koordinat: { lat: 1.5988, lng: 101.5086 },
    anggaran: 990_000_000,
    nilaiKontrak: 955_000_000,
    status: 'pelaksanaan',
    kategoriPekerjaan: 'rutin',
    jenisProyek: 'fisik',
    tahunAnggaran: 2026,
    program: 'Pengelolaan Sumber Daya Air',
    kegiatan: 'Operasi dan Pemeliharaan Drainase',
    subKegiatan: 'Normalisasi Saluran Rutin',
    health: 'warning',
    progressFisik: 31,
    progressKeuangan: 25,
    deviasi: 6,
    tanggalMulai: '2026-04-01',
    tanggalSelesai: '2026-07-30',
    kontraktor: 'CV. Pelintung Jaya',
    pptk: 'Rudi Hartono, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [makeSurvey('sda-010', 10, { lat: 1.5988, lng: 101.5086 }, 'submitted', 'Saluran primer tertutup vegetasi dan sedimen lunak.', 'Aliran lambat menuju outlet saat pasang.')],
    rabList: [makeRab('sda-010', 955_000_000, 'submitted')],
    laporanHarian: [makeReport('sda-010', { lat: 1.5988, lng: 101.5086 }, 31, false, 'Pembersihan vegetasi dan pengerukan manual dimulai dari hilir.')],
    catatanPengawasan: [],
    masalah: [makeIssue('sda-010', 10, 'sedang', 'in_progress', 'Cuaca menghambat normalisasi', 'Hujan harian membuat alat sulit masuk ke tanggul kerja.')],
    chat: [],
    assignedUsers: ['u1', 'u4', 'u6'],
    createdAt: '2026-03-20T08:00:00',
    updatedAt: '2026-05-19T14:00:00',
  },
  {
    id: 'sda-011',
    kode: 'SDA-KSL-017/2026',
    nama: 'Konsultan Perencanaan Kolam Retensi Bukit Kapur',
    lokasi: 'Kawasan Bukit Kapur, Kel. Gurun Panjang',
    kecamatan: 'Bukit Kapur',
    koordinat: { lat: 1.5884, lng: 101.3946 },
    anggaran: 780_000_000,
    nilaiKontrak: 748_000_000,
    status: 'monitoring',
    kategoriPekerjaan: 'pl',
    jenisProyek: 'konsultan_perencanaan',
    tahunAnggaran: 2026,
    program: 'Pengelolaan Sumber Daya Air',
    kegiatan: 'Perencanaan Pengendalian Banjir',
    subKegiatan: 'Dokumen Perencanaan Teknis SDA',
    health: 'on_track',
    progressFisik: 82,
    progressKeuangan: 70,
    deviasi: 12,
    tanggalMulai: '2026-02-15',
    tanggalSelesai: '2026-06-30',
    kontraktor: 'CV. Konsultan Mitra Riau',
    konsultanPerencana: 'CV. Konsultan Mitra Riau',
    pptk: 'Siti Rahmawati, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [makeSurvey('sda-011', 11, { lat: 1.5884, lng: 101.3946 }, 'approved', 'Lokasi calon kolam retensi memiliki cekungan alami dan lahan relatif tersedia.', 'Perlu kajian hidrologi, pembebasan lahan, dan outlet pengendali.')],
    rabList: [makeRab('sda-011', 748_000_000, 'approved')],
    laporanHarian: [makeReport('sda-011', { lat: 1.5884, lng: 101.3946 }, 82, true, 'Draft DED dan BOQ masuk tahap review PPK.')],
    catatanPengawasan: [],
    masalah: [],
    chat: [],
    assignedUsers: ['u1', 'u3', 'u5', 'u7'],
    createdAt: '2026-02-01T08:00:00',
    updatedAt: '2026-05-21T10:00:00',
  },
  {
    id: 'sda-012',
    kode: 'SDA-DRN-018/2026',
    nama: 'Rehabilitasi Saluran Jalan Hasanuddin',
    lokasi: 'Jl. Hasanuddin, Kel. Rimba Sekampung',
    kecamatan: 'Dumai Kota',
    koordinat: { lat: 1.6758, lng: 101.4544 },
    anggaran: 1_330_000_000,
    nilaiKontrak: 1_288_000_000,
    status: 'pelaksanaan',
    kategoriPekerjaan: 'lelang',
    jenisProyek: 'fisik',
    tahunAnggaran: 2026,
    program: 'Pengelolaan Sumber Daya Air',
    kegiatan: 'Pengelolaan Drainase Perkotaan',
    subKegiatan: 'Rehabilitasi Drainase Perkotaan',
    health: 'warning',
    progressFisik: 47,
    progressKeuangan: 62,
    deviasi: -15,
    tanggalMulai: '2026-02-28',
    tanggalSelesai: '2026-08-20',
    kontraktor: 'PT. Bina Saluran Dumai',
    konsultanPengawasan: 'PT. Pengawas Prima',
    pptk: 'Siti Rahmawati, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [makeSurvey('sda-012', 12, { lat: 1.6758, lng: 101.4544 }, 'approved', 'Tutup saluran banyak rusak dan membahayakan pengguna jalan.', 'Aliran masih berjalan tetapi kapasitas berkurang akibat sedimentasi.')],
    rabList: [makeRab('sda-012', 1_288_000_000, 'approved')],
    laporanHarian: [makeReport('sda-012', { lat: 1.6758, lng: 101.4544 }, 47, false, 'Pekerjaan tutup saluran menunggu pengiriman precast tambahan.')],
    catatanPengawasan: [],
    masalah: [makeIssue('sda-012', 12, 'tinggi', 'open', 'Dokumen mutu precast belum lengkap', 'Sertifikat mutu material belum diserahkan lengkap oleh penyedia.')],
    chat: [],
    assignedUsers: ['u1', 'u3', 'u6', 'u8'],
    createdAt: '2026-02-12T08:00:00',
    updatedAt: '2026-05-23T12:00:00',
  },
  {
    id: 'sda-013',
    kode: 'SDA-OPR-019/2026',
    nama: 'Perbaikan Pompa Mobile Genangan Sudirman',
    lokasi: 'Jl. Jenderal Sudirman, Kel. Teluk Binjai',
    kecamatan: 'Dumai Timur',
    koordinat: { lat: 1.6726, lng: 101.4695 },
    anggaran: 520_000_000,
    nilaiKontrak: 502_000_000,
    status: 'pelaksanaan',
    kategoriPekerjaan: 'rutin',
    jenisProyek: 'fisik',
    tahunAnggaran: 2026,
    program: 'Pengelolaan Sumber Daya Air',
    kegiatan: 'Operasi Sarana Pengendali Genangan',
    subKegiatan: 'Pemeliharaan Pompa dan Peralatan',
    health: 'kritis',
    progressFisik: 9,
    progressKeuangan: 18,
    deviasi: -9,
    tanggalMulai: '2026-05-01',
    tanggalSelesai: '2026-06-25',
    kontraktor: 'CV. Teknik Pompa Riau',
    pptk: 'Rudi Hartono, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [makeSurvey('sda-013', 13, { lat: 1.6726, lng: 101.4695 }, 'approved', 'Pompa mobile tidak optimal saat genangan di koridor Sudirman.', 'Risiko respon lambat saat hujan ekstrem dan pasang tinggi.')],
    rabList: [makeRab('sda-013', 502_000_000, 'rejected')],
    laporanHarian: [],
    catatanPengawasan: [],
    masalah: [makeIssue('sda-013', 13, 'kritis', 'open', 'Sparepart pompa belum tersedia', 'Komponen impeller belum diterima sehingga perbaikan utama tertunda.')],
    chat: [],
    assignedUsers: ['u1', 'u4', 'u6'],
    createdAt: '2026-04-26T08:00:00',
    updatedAt: '2026-05-22T13:00:00',
  },
  {
    id: 'sda-014',
    kode: 'SDA-DRN-020/2026',
    nama: 'Pembersihan Saluran Jalan Dock Yard',
    lokasi: 'Jl. Dock Yard, Kel. Pangkalan Sesai',
    kecamatan: 'Dumai Barat',
    koordinat: { lat: 1.6734, lng: 101.4149 },
    anggaran: 380_000_000,
    nilaiKontrak: 365_000_000,
    status: 'pelaksanaan',
    kategoriPekerjaan: 'rutin',
    jenisProyek: 'fisik',
    tahunAnggaran: 2026,
    program: 'Pengelolaan Sumber Daya Air',
    kegiatan: 'Operasi dan Pemeliharaan Drainase',
    subKegiatan: 'Pembersihan Saluran Rutin',
    health: 'on_track',
    progressFisik: 93,
    progressKeuangan: 88,
    deviasi: 5,
    tanggalMulai: '2026-04-05',
    tanggalSelesai: '2026-05-30',
    kontraktor: 'CV. Bersih Saluran',
    pptk: 'Siti Rahmawati, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [makeSurvey('sda-014', 14, { lat: 1.6734, lng: 101.4149 }, 'approved', 'Saluran dipenuhi sampah dan lumpur dekat kawasan pelabuhan.', 'Perlu pembersihan rutin untuk menjaga aliran ke outlet.')],
    rabList: [makeRab('sda-014', 365_000_000, 'approved')],
    laporanHarian: [makeReport('sda-014', { lat: 1.6734, lng: 101.4149 }, 93, true, 'Pembersihan hampir selesai, sisa pengangkutan material sedimen.')],
    catatanPengawasan: [],
    masalah: [],
    chat: [],
    assignedUsers: ['u1', 'u3', 'u6'],
    createdAt: '2026-03-29T08:00:00',
    updatedAt: '2026-05-24T08:00:00',
  },
  {
    id: 'sda-015',
    kode: 'SDA-TGL-021/2026',
    nama: 'Perkuatan Tanggul Parit Pisang Berembang',
    lokasi: 'Parit Pisang Berembang, Kel. Bagan Besar',
    kecamatan: 'Bukit Kapur',
    koordinat: { lat: 1.5749, lng: 101.4317 },
    anggaran: 2_760_000_000,
    nilaiKontrak: 2_680_000_000,
    status: 'pelaksanaan',
    kategoriPekerjaan: 'lelang',
    jenisProyek: 'fisik',
    tahunAnggaran: 2026,
    program: 'Pengelolaan Sumber Daya Air',
    kegiatan: 'Pengendalian Banjir dan Pengamanan Tebing',
    subKegiatan: 'Perkuatan Tanggul dan Tebing',
    health: 'warning',
    progressFisik: 64,
    progressKeuangan: 55,
    deviasi: 9,
    tanggalMulai: '2026-02-10',
    tanggalSelesai: '2026-09-30',
    kontraktor: 'PT. Tanggul Riau Konstruksi',
    konsultanPengawasan: 'PT. Pengawas Prima',
    pptk: 'Rudi Hartono, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [makeSurvey('sda-015', 15, { lat: 1.5749, lng: 101.4317 }, 'approved', 'Tebing parit mengalami gerusan dan tanggul rendah di beberapa titik.', 'Risiko limpasan ke area kebun dan permukiman rendah saat hujan besar.')],
    rabList: [makeRab('sda-015', 2_680_000_000, 'approved')],
    laporanHarian: [makeReport('sda-015', { lat: 1.5749, lng: 101.4317 }, 64, true, 'Pemasangan cerucuk dan timbunan pilihan dilanjutkan di STA 0+420.')],
    catatanPengawasan: [],
    masalah: [makeIssue('sda-015', 15, 'sedang', 'resolved', 'Keterlambatan material geotekstil', 'Pengiriman geotekstil terlambat dua hari dan sudah diterima di lokasi.')],
    chat: [],
    assignedUsers: ['u1', 'u4', 'u6', 'u8'],
    createdAt: '2026-01-30T08:00:00',
    updatedAt: '2026-05-24T10:00:00',
  },
  {
    id: 'sda-016',
    kode: 'SDA-DRN-022/2026',
    nama: 'Rekonstruksi Outlet Drainase Teluk Makmur',
    lokasi: 'Outlet Teluk Makmur, Kel. Teluk Makmur',
    kecamatan: 'Medang Kampai',
    koordinat: { lat: 1.6841, lng: 101.5394 },
    anggaran: 1_480_000_000,
    nilaiKontrak: 1_430_000_000,
    status: 'pelaksanaan',
    kategoriPekerjaan: 'pl',
    jenisProyek: 'fisik',
    tahunAnggaran: 2026,
    program: 'Pengelolaan Sumber Daya Air',
    kegiatan: 'Pengendalian Banjir dan Genangan',
    subKegiatan: 'Rekonstruksi Outlet Drainase',
    health: 'kritis',
    progressFisik: 43,
    progressKeuangan: 70,
    deviasi: -27,
    tanggalMulai: '2026-03-01',
    tanggalSelesai: '2026-08-05',
    kontraktor: 'CV. Lautan Biru Dumai',
    pptk: 'Rudi Hartono, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [makeSurvey('sda-016', 16, { lat: 1.6841, lng: 101.5394 }, 'approved', 'Outlet lama rusak akibat abrasi dan pasang surut.', 'Air balik masuk ke saluran saat pasang maksimum.')],
    rabList: [makeRab('sda-016', 1_430_000_000, 'approved')],
    laporanHarian: [makeReport('sda-016', { lat: 1.6841, lng: 101.5394 }, 43, false, 'Pekerjaan struktur outlet menunggu pasangan batu pelindung selesai.')],
    catatanPengawasan: [],
    masalah: [makeIssue('sda-016', 16, 'kritis', 'open', 'Risiko rob saat pekerjaan outlet', 'Pekerjaan berada di zona pasang surut sehingga perlu penjadwalan ulang jam kerja.')],
    chat: [],
    assignedUsers: ['u1', 'u4', 'u6'],
    createdAt: '2026-02-20T08:00:00',
    updatedAt: '2026-05-24T09:00:00',
  },
  {
    id: 'sda-017',
    kode: 'SDA-DRN-023/2026',
    nama: 'Peningkatan Drainase Jalan Cempedak',
    lokasi: 'Jl. Cempedak, Kel. Ratu Sima',
    kecamatan: 'Dumai Selatan',
    koordinat: { lat: 1.6478, lng: 101.4268 },
    anggaran: 1_120_000_000,
    nilaiKontrak: 1_075_000_000,
    status: 'siap_dilaksanakan',
    kategoriPekerjaan: 'pl',
    jenisProyek: 'fisik',
    tahunAnggaran: 2026,
    program: 'Pengelolaan Sumber Daya Air',
    kegiatan: 'Pengelolaan Drainase Lingkungan',
    subKegiatan: 'Peningkatan Saluran Lingkungan',
    health: 'on_track',
    progressFisik: 4,
    progressKeuangan: 3,
    deviasi: 1,
    tanggalMulai: '2026-06-03',
    tanggalSelesai: '2026-09-15',
    kontraktor: 'CV. Karya Selatan',
    pptk: 'Siti Rahmawati, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [makeSurvey('sda-017', 17, { lat: 1.6478, lng: 101.4268 }, 'approved', 'Saluran tanah tidak stabil dan perlu peningkatan permanen.', 'Warga melaporkan genangan berulang pada titik rendah.')],
    rabList: [makeRab('sda-017', 1_075_000_000, 'approved')],
    laporanHarian: [],
    catatanPengawasan: [],
    masalah: [],
    chat: [],
    assignedUsers: ['u1', 'u3'],
    createdAt: '2026-05-12T08:00:00',
    updatedAt: '2026-05-20T08:00:00',
  },
  {
    id: 'sda-018',
    kode: 'SDA-DRN-024/2026',
    nama: 'Rehabilitasi Drainase Jalan Datuk Laksamana',
    lokasi: 'Jl. Datuk Laksamana, Kel. Buluh Kasap',
    kecamatan: 'Dumai Timur',
    koordinat: { lat: 1.6889, lng: 101.4567 },
    anggaran: 1_680_000_000,
    nilaiKontrak: 1_620_000_000,
    status: 'pelaksanaan',
    kategoriPekerjaan: 'lelang',
    jenisProyek: 'fisik',
    tahunAnggaran: 2026,
    program: 'Pengelolaan Sumber Daya Air',
    kegiatan: 'Pengelolaan Drainase Perkotaan',
    subKegiatan: 'Rehabilitasi Drainase Perkotaan',
    health: 'warning',
    progressFisik: 58,
    progressKeuangan: 44,
    deviasi: 14,
    tanggalMulai: '2026-02-17',
    tanggalSelesai: '2026-08-25',
    kontraktor: 'PT. Riau Drainase Utama',
    konsultanPengawasan: 'PT. Pengawas Prima',
    pptk: 'Siti Rahmawati, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [makeSurvey('sda-018', 18, { lat: 1.6889, lng: 101.4567 }, 'approved', 'Saluran tertutup bangunan akses warga dan beberapa penutup rusak.', 'Perlu penataan ulang akses dan normalisasi saluran.')],
    rabList: [makeRab('sda-018', 1_620_000_000, 'submitted')],
    laporanHarian: [makeReport('sda-018', { lat: 1.6889, lng: 101.4567 }, 58, false, 'Pekerjaan fisik maju, administrasi opname belum lengkap.')],
    catatanPengawasan: [],
    masalah: [makeIssue('sda-018', 18, 'tinggi', 'open', 'Dokumen opname belum lengkap', 'Berita acara opname dan dokumentasi volume belum lengkap untuk pembayaran termin.')],
    chat: [],
    assignedUsers: ['u1', 'u3', 'u6', 'u8'],
    createdAt: '2026-02-01T08:00:00',
    updatedAt: '2026-05-24T11:00:00',
  },
  {
    id: 'sda-019',
    kode: 'SDA-OPR-025/2026',
    nama: 'Operasi Pembersihan Rumah Pompa Bumi Ayu',
    lokasi: 'Rumah Pompa Bumi Ayu, Kel. Bumi Ayu',
    kecamatan: 'Bukit Kapur',
    koordinat: { lat: 1.6253, lng: 101.4102 },
    anggaran: 460_000_000,
    nilaiKontrak: 445_000_000,
    status: 'monitoring',
    kategoriPekerjaan: 'rutin',
    jenisProyek: 'fisik',
    tahunAnggaran: 2026,
    program: 'Pengelolaan Sumber Daya Air',
    kegiatan: 'Operasi Infrastruktur Pengendali Genangan',
    subKegiatan: 'Operasi Rumah Pompa',
    health: 'on_track',
    progressFisik: 77,
    progressKeuangan: 74,
    deviasi: 3,
    tanggalMulai: '2026-03-15',
    tanggalSelesai: '2026-07-15',
    kontraktor: 'CV. Pompa Jaya Teknik',
    pptk: 'Rudi Hartono, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [makeSurvey('sda-019', 19, { lat: 1.6253, lng: 101.4102 }, 'approved', 'Area inlet pompa memerlukan pembersihan berkala dan perawatan panel.', 'Kinerja pompa turun saat sampah menumpuk di trash rack.')],
    rabList: [makeRab('sda-019', 445_000_000, 'approved')],
    laporanHarian: [makeReport('sda-019', { lat: 1.6253, lng: 101.4102 }, 77, true, 'Pembersihan trash rack dan uji operasi pompa selesai.')],
    catatanPengawasan: [],
    masalah: [],
    chat: [],
    assignedUsers: ['u1', 'u4', 'u6'],
    createdAt: '2026-03-01T08:00:00',
    updatedAt: '2026-05-23T16:00:00',
  },
  {
    id: 'sda-020',
    kode: 'SDA-DRN-026/2026',
    nama: 'Pembangunan Saluran Penghubung Bagan Keladi',
    lokasi: 'Jl. Bagan Keladi, Kel. Bagan Keladi',
    kecamatan: 'Dumai Barat',
    koordinat: { lat: 1.6356, lng: 101.3877 },
    anggaran: 2_040_000_000,
    nilaiKontrak: 1_980_000_000,
    status: 'rab_disusun',
    kategoriPekerjaan: 'lelang',
    jenisProyek: 'fisik',
    tahunAnggaran: 2026,
    program: 'Pengelolaan Sumber Daya Air',
    kegiatan: 'Pengendalian Banjir dan Genangan',
    subKegiatan: 'Pembangunan Saluran Penghubung',
    health: 'warning',
    progressFisik: 6,
    progressKeuangan: 0,
    deviasi: 6,
    tanggalMulai: '2026-06-10',
    tanggalSelesai: '2026-11-30',
    kontraktor: 'PT. Saluran Barat Dumai',
    konsultanPerencana: 'CV. Konsultan Mitra Riau',
    pptk: 'Siti Rahmawati, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [makeSurvey('sda-020', 20, { lat: 1.6356, lng: 101.3877 }, 'rejected', 'Rencana trase saluran masih perlu verifikasi ulang.', 'Ada potensi konflik lahan dan elevasi outlet belum final.')],
    rabList: [makeRab('sda-020', 1_980_000_000, 'draft')],
    laporanHarian: [],
    catatanPengawasan: [],
    masalah: [makeIssue('sda-020', 20, 'tinggi', 'open', 'Survey perlu revisi trase', 'Data elevasi dan batas lahan belum cukup untuk menetapkan trase final.')],
    chat: [],
    assignedUsers: ['u1', 'u3', 'u5'],
    createdAt: '2026-05-05T08:00:00',
    updatedAt: '2026-05-22T08:00:00',
  },
]

export const DUMMY_PROJECTS: Proyek[] = [
  ...ADDITIONAL_SDA_PACKAGES,
  {
    id: 'p1',
    kode: 'PU-DRN-001/2026',
    nama: 'Rehabilitasi Drainase Jl. Sultan Syarif Kasim',
    lokasi: 'Jl. Sultan Syarif Kasim, Kel. Ratu Sima',
    kecamatan: 'Dumai Kota',
    koordinat: { lat: 1.6781, lng: 101.4473 },
    anggaran: 2_850_000_000,
    nilaiKontrak: 2_750_000_000,
    status: 'pelaksanaan',
    kategoriPekerjaan: 'lelang',
    health: 'on_track',
    progressFisik: 65,
    progressKeuangan: 58,
    deviasi: -7,
    tanggalMulai: '2026-02-01',
    tanggalSelesai: '2026-07-31',
    kontraktor: 'PT. Bangun Riau Jaya',
    konsultanPerencana: 'CV. Konsultan Mitra Riau',
    konsultanPengawasan: 'PT. Pengawas Prima',
    pptk: 'Siti Rahmawati, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [
      {
        id: 's1',
        proyekId: 'p1',
        tanggal: '2026-01-15',
        userId: 'u5',
        userName: 'Tim Perencanaan A',
        koordinat: { lat: 1.6781, lng: 101.4473 },
        kondisiEksisting: 'Drainase eksisting kondisi rusak berat, banyak sedimentasi dan vegetasi liar. Kapasitas tampung sangat berkurang akibat penyempitan. Dinding saluran retak dan sebagian ambruk.',
        dimensi: { panjang: 850, lebar: 1.2, tinggi: 1.0 },
        material: 'Beton bertulang K-250, pasangan batu kali 1:4',
        permasalahan: 'Banjir rutin saat hujan >30mm/jam, genangan mencapai 60cm di badan jalan. Warga mengeluh sejak 3 tahun terakhir. Ada 2 titik ambruk kritis.',
        rekomendasi: 'Normalisasi saluran, perbaikan dinding, pemasangan tutup U-ditch precast',
        foto: [
          { id: 'f1', url: '/uploads/survey-p1-1.jpg', uploadedAt: '2026-01-15T09:30:00', uploadedBy: 'Tim Perencanaan A', keterangan: 'Kondisi eksisting titik 1' },
          { id: 'f2', url: '/uploads/survey-p1-2.jpg', uploadedAt: '2026-01-15T09:45:00', uploadedBy: 'Tim Perencanaan A', keterangan: 'Titik ambruk kritis' },
          { id: 'f3', url: '/uploads/survey-p1-3.jpg', uploadedAt: '2026-01-15T10:00:00', uploadedBy: 'Tim Perencanaan A', keterangan: 'Kondisi sekitar permukiman' },
        ],
        status: 'submitted',
        createdAt: '2026-01-15T09:00:00',
      },
    ],
    rabList: [
      {
        id: 'rab1',
        proyekId: 'p1',
        versi: 'v1',
        versionNumber: 1,
        items: [
          { no: '1', uraian: 'Pekerjaan Persiapan', satuan: 'Ls', volume: 1, hargaSatuan: 45_000_000, total: 45_000_000 },
          { no: '2', uraian: 'Galian Saluran', satuan: 'm³', volume: 1020, hargaSatuan: 85_000, total: 86_700_000 },
          { no: '3', uraian: 'Pasangan Batu Kali 1:4', satuan: 'm³', volume: 510, hargaSatuan: 850_000, total: 433_500_000 },
          { no: '4', uraian: 'Beton K-250 Dinding', satuan: 'm³', volume: 204, hargaSatuan: 1_250_000, total: 255_000_000 },
          { no: '5', uraian: 'U-Ditch Precast 120x120', satuan: 'unit', volume: 850, hargaSatuan: 1_850_000, total: 1_572_500_000 },
          { no: '6', uraian: 'Pekerjaan Akhir', satuan: 'Ls', volume: 1, hargaSatuan: 357_300_000, total: 357_300_000 },
        ],
        totalAnggaran: 2_750_000_000,
        uploadedBy: 'CV. Konsultan Mitra Riau',
        uploadedAt: '2026-01-20T10:00:00',
        status: 'approved',
      },
    ],
    laporanHarian: [
      {
        id: 'lh1',
        proyekId: 'p1',
        tanggal: '2026-04-26',
        userId: 'u3',
        userName: 'Siti Rahmawati, ST',
        uraianPekerjaan: 'Pemasangan U-Ditch precast STA 0+250 s/d 0+310. Total 60 unit terpasang hari ini. Pekerjaan galian lanjutan STA 0+310 s/d 0+380 sebanyak 84 m³.',
        progressFisik: 65,
        progressKumulatif: 65,
        cuaca: 'berawan',
        koordinat: { lat: 1.6781, lng: 101.4473 },
        foto: [
          { id: 'fl1', url: '/uploads/laporan-p1-1.jpg', uploadedAt: '2026-04-26T08:00:00', uploadedBy: 'Siti Rahmawati, ST', keterangan: 'Foto pagi - kondisi awal' },
          { id: 'fl2', url: '/uploads/laporan-p1-2.jpg', uploadedAt: '2026-04-26T12:00:00', uploadedBy: 'Siti Rahmawati, ST', keterangan: 'Pemasangan U-Ditch' },
          { id: 'fl3', url: '/uploads/laporan-p1-3.jpg', uploadedAt: '2026-04-26T16:00:00', uploadedBy: 'Siti Rahmawati, ST', keterangan: 'Foto sore - kemajuan harian' },
        ],
        disetujui: true,
        disetujuiOleh: 'Ir. Ahmad Fauzi, MT',
        createdAt: '2026-04-26T07:30:00',
      },
    ],
    catatanPengawasan: [
      {
        id: 'cp1',
        proyekId: 'p1',
        userId: 'u6',
        userName: 'Tim Pengawasan B',
        deskripsi: 'Pemasangan U-Ditch sudah sesuai spesifikasi teknis. Sambungan antar unit rapi dan waterproofing sudah diaplikasikan.',
        rekomendasi: 'Lanjutkan pemasangan. Pastikan elevasi sesuai dengan gambar desain pada STA berikutnya.',
        status: 'sesuai',
        foto: [],
        tanggal: '2026-04-26',
        createdAt: '2026-04-26T14:00:00',
      },
    ],
    masalah: [],
    chat: [
      {
        id: 'ch1',
        proyekId: 'p1',
        userId: 'u3',
        userName: 'Siti Rahmawati',
        userRole: 'pptk',
        message: 'Progress hari ini berjalan lancar. Sudah 60 unit U-Ditch terpasang.',
        timestamp: '2026-04-26T16:30:00',
        type: 'text',
      },
      {
        id: 'ch2',
        proyekId: 'p1',
        userId: 'u1',
        userName: 'Ir. Ahmad Fauzi',
        userRole: 'ppk',
        message: 'Bagus. Pastikan kualitas sambungan dicek sebelum timbunan dilaksanakan.',
        timestamp: '2026-04-26T16:45:00',
        type: 'text',
      },
    ],
    assignedUsers: ['u1', 'u3', 'u6', 'u7', 'u8'],
    createdAt: '2026-01-10T08:00:00',
    updatedAt: '2026-04-26T16:30:00',
  },
  {
    id: 'p2',
    kode: 'PU-JLN-002/2026',
    nama: 'Peningkatan Jalan Soekarno Hatta Segmen II',
    lokasi: 'Jl. Soekarno Hatta, Kel. Bumi Ayu',
    kecamatan: 'Bukit Kapur',
    koordinat: { lat: 1.6520, lng: 101.4220 },
    anggaran: 5_200_000_000,
    nilaiKontrak: 5_050_000_000,
    status: 'pelaksanaan',
    kategoriPekerjaan: 'lelang',
    health: 'kritis',
    progressFisik: 15,
    progressKeuangan: 30,
    deviasi: -15,
    tanggalMulai: '2026-01-15',
    tanggalSelesai: '2026-06-30',
    kontraktor: 'PT. Karya Dumai Mandiri',
    konsultanPengawasan: 'PT. Pengawas Prima',
    pptk: 'Rudi Hartono, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [
      {
        id: 's2',
        proyekId: 'p2',
        tanggal: '2025-12-10',
        userId: 'u5',
        userName: 'Tim Perencanaan A',
        koordinat: { lat: 1.6520, lng: 101.4220 },
        kondisiEksisting: 'Jalan aspal eksisting rusak berat. Berlubang di hampir seluruh segmen, lebar efektif hanya 5m dari rencana 7m.',
        dimensi: { panjang: 1200, lebar: 7, tinggi: 0.15 },
        material: 'AC-WC, AC-BC, Lapis Pondasi Agregat Kelas A',
        permasalahan: 'Banyak lubang besar, drainase tepi jalan tersumbat. Konektivitas ke kawasan industri terganggu.',
        foto: [
          { id: 'f4', url: '/uploads/survey-p2-1.jpg', uploadedAt: '2025-12-10T09:00:00', uploadedBy: 'Tim Perencanaan A', keterangan: 'Kondisi jalan rusak berat' },
          { id: 'f5', url: '/uploads/survey-p2-2.jpg', uploadedAt: '2025-12-10T09:30:00', uploadedBy: 'Tim Perencanaan A', keterangan: 'Lubang-lubang kritis' },
          { id: 'f6', url: '/uploads/survey-p2-3.jpg', uploadedAt: '2025-12-10T10:00:00', uploadedBy: 'Tim Perencanaan A', keterangan: 'Drainase tersumbat' },
        ],
        status: 'submitted',
        createdAt: '2025-12-10T09:00:00',
      },
    ],
    rabList: [
      {
        id: 'rab2',
        proyekId: 'p2',
        versi: 'v1',
        versionNumber: 1,
        items: [
          { no: '1', uraian: 'Mobilisasi & Demobilisasi', satuan: 'Ls', volume: 1, hargaSatuan: 150_000_000, total: 150_000_000 },
          { no: '2', uraian: 'Pekerjaan Tanah & Persiapan', satuan: 'Ls', volume: 1, hargaSatuan: 200_000_000, total: 200_000_000 },
          { no: '3', uraian: 'Lapis Pondasi Agregat Kelas A', satuan: 'm³', volume: 2520, hargaSatuan: 425_000, total: 1_071_000_000 },
          { no: '4', uraian: 'AC-BC Lapis Antara', satuan: 'ton', volume: 1848, hargaSatuan: 1_250_000, total: 2_310_000_000 },
          { no: '5', uraian: 'AC-WC Lapis Aus', satuan: 'ton', volume: 840, hargaSatuan: 1_380_000, total: 1_159_200_000 },
          { no: '6', uraian: 'Drainase Tepi Jalan', satuan: 'm', volume: 2400, hargaSatuan: 66_583, total: 159_800_000 },
        ],
        totalAnggaran: 5_050_000_000,
        uploadedBy: 'CV. Konsultan Mitra Riau',
        uploadedAt: '2025-12-20T10:00:00',
        status: 'approved',
      },
    ],
    laporanHarian: [],
    catatanPengawasan: [],
    masalah: [
      {
        id: 'm1',
        proyekId: 'p2',
        judul: 'Kontraktor tidak mobilisasi alat berat sesuai jadwal',
        deskripsi: 'Asphalt finisher dan motor grader belum ada di lokasi padahal sudah melewati minggu ke-6 pelaksanaan. Progres fisik sangat jauh di bawah kurva S.',
        status: 'in_progress',
        prioritas: 'kritis',
        dilaporkanOleh: 'u4',
        dilaporkanOlehName: 'Rudi Hartono, ST',
        tanggal: '2026-04-10',
        foto: [],
        createdAt: '2026-04-10T10:00:00',
      },
    ],
    chat: [],
    assignedUsers: ['u1', 'u4', 'u8'],
    createdAt: '2026-01-05T08:00:00',
    updatedAt: '2026-04-26T08:00:00',
  },
  {
    id: 'p3',
    kode: 'PU-DRN-003/2026',
    nama: 'Pembangunan Box Culvert Sei Dumai',
    lokasi: 'Jl. Pattimura, Kel. Jaya Mukti',
    kecamatan: 'Dumai Timur',
    koordinat: { lat: 1.6920, lng: 101.4680 },
    anggaran: 3_100_000_000,
    nilaiKontrak: 2_980_000_000,
    status: 'pelaksanaan',
    kategoriPekerjaan: 'pl',
    health: 'warning',
    progressFisik: 40,
    progressKeuangan: 52,
    deviasi: -12,
    tanggalMulai: '2026-02-15',
    tanggalSelesai: '2026-08-15',
    kontraktor: 'CV. Bersama Maju',
    konsultanPengawasan: 'PT. Pengawas Prima',
    pptk: 'Siti Rahmawati, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [
      {
        id: 's3',
        proyekId: 'p3',
        tanggal: '2026-01-20',
        userId: 'u5',
        userName: 'Tim Perencanaan A',
        koordinat: { lat: 1.6920, lng: 101.4680 },
        kondisiEksisting: 'Gorong-gorong eksisting berdiameter 80cm sudah tidak mampu menampung debit banjir 10 tahunan. Material besi berkarat.',
        dimensi: { panjang: 120, lebar: 3.0, tinggi: 2.5 },
        material: 'Beton K-300 bertulang, waterproofing membrane',
        permasalahan: 'Banjir tahunan area sekitar, merendam 3 RT. Kapasitas tampung kurang dari 30% kebutuhan.',
        foto: [
          { id: 'f7', url: '/uploads/survey-p3-1.jpg', uploadedAt: '2026-01-20T08:00:00', uploadedBy: 'Tim Perencanaan A', keterangan: 'Gorong-gorong existing' },
          { id: 'f8', url: '/uploads/survey-p3-2.jpg', uploadedAt: '2026-01-20T08:30:00', uploadedBy: 'Tim Perencanaan A', keterangan: 'Kondisi banjir' },
          { id: 'f9', url: '/uploads/survey-p3-3.jpg', uploadedAt: '2026-01-20T09:00:00', uploadedBy: 'Tim Perencanaan A', keterangan: 'Titik kritis' },
        ],
        status: 'submitted',
        createdAt: '2026-01-20T08:00:00',
      },
    ],
    rabList: [],
    laporanHarian: [],
    catatanPengawasan: [],
    masalah: [
      {
        id: 'm2',
        proyekId: 'p3',
        judul: 'Material bekisting tidak sesuai spesifikasi',
        deskripsi: 'Bekisting yang digunakan kontraktor adalah kayu lapis biasa bukan plywood phenol yang disyaratkan, berisiko terhadap kualitas beton.',
        status: 'open',
        prioritas: 'sedang',
        dilaporkanOleh: 'u6',
        dilaporkanOlehName: 'Tim Pengawasan B',
        tanggal: '2026-04-20',
        foto: [],
        createdAt: '2026-04-20T11:00:00',
      },
    ],
    chat: [],
    assignedUsers: ['u1', 'u3', 'u6', 'u8'],
    createdAt: '2026-01-10T08:00:00',
    updatedAt: '2026-04-25T14:00:00',
  },
  {
    id: 'p4',
    kode: 'PU-JLN-004/2026',
    nama: 'Peningkatan Jalan Putri Tujuh Segmen I',
    lokasi: 'Jl. Putri Tujuh, Kel. Tanjung Palas',
    kecamatan: 'Dumai Kota',
    koordinat: { lat: 1.6850, lng: 101.4390 },
    anggaran: 4_500_000_000,
    nilaiKontrak: 4_350_000_000,
    status: 'pelaksanaan',
    kategoriPekerjaan: 'pl',
    health: 'on_track',
    progressFisik: 45,
    progressKeuangan: 44,
    deviasi: 1,
    tanggalMulai: '2026-03-01',
    tanggalSelesai: '2026-09-30',
    kontraktor: 'PT. Nusa Karya Dumai',
    pptk: 'Rudi Hartono, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [],
    rabList: [],
    laporanHarian: [],
    catatanPengawasan: [],
    masalah: [],
    chat: [],
    assignedUsers: ['u1', 'u4'],
    createdAt: '2026-02-20T08:00:00',
    updatedAt: '2026-04-26T08:00:00',
  },
  {
    id: 'p5',
    kode: 'PU-DRN-005/2026',
    nama: 'Normalisasi Parit Sungai Binti',
    lokasi: 'Kawasan Sungai Binti, Kel. Bukit Timah',
    kecamatan: 'Dumai Timur',
    koordinat: { lat: 1.7050, lng: 101.4780 },
    anggaran: 1_800_000_000,
    nilaiKontrak: 1_720_000_000,
    status: 'pelaksanaan',
    kategoriPekerjaan: 'rutin',
    health: 'kritis',
    progressFisik: 8,
    progressKeuangan: 20,
    deviasi: -12,
    tanggalMulai: '2026-01-20',
    tanggalSelesai: '2026-05-20',
    kontraktor: 'CV. Sejahtera Riau',
    pptk: 'Siti Rahmawati, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [],
    rabList: [],
    laporanHarian: [],
    catatanPengawasan: [],
    masalah: [
      {
        id: 'm3',
        proyekId: 'p5',
        judul: 'Konflik lahan warga belum selesai',
        deskripsi: '3 bidang tanah warga yang terdampak normalisasi belum ada kesepakatan ganti rugi. Kontraktor tidak bisa mulai kerja di area tersebut.',
        status: 'open',
        prioritas: 'kritis',
        dilaporkanOleh: 'u3',
        dilaporkanOlehName: 'Siti Rahmawati, ST',
        tanggal: '2026-02-10',
        foto: [],
        createdAt: '2026-02-10T09:00:00',
      },
    ],
    chat: [],
    assignedUsers: ['u1', 'u3'],
    createdAt: '2026-01-10T08:00:00',
    updatedAt: '2026-04-20T08:00:00',
  },
  {
    id: 'p6',
    kode: 'PU-JLN-006/2026',
    nama: 'Pembangunan Jembatan Sei Mesjid',
    lokasi: 'Jl. Imam Bonjol, Kel. Rimba Sekampung',
    kecamatan: 'Medang Kampai',
    koordinat: { lat: 1.6380, lng: 101.4050 },
    anggaran: 8_500_000_000,
    nilaiKontrak: 8_200_000_000,
    status: 'survey',
    kategoriPekerjaan: 'lelang',
    health: 'warning',
    progressFisik: 22,
    progressKeuangan: 35,
    deviasi: -13,
    tanggalMulai: '2026-02-01',
    tanggalSelesai: '2026-12-31',
    kontraktor: 'PT. Wijaya Karya Tbk',
    pptk: 'Rudi Hartono, ST',
    ppk: 'Ir. Ahmad Fauzi, MT',
    surveys: [],
    rabList: [],
    laporanHarian: [],
    catatanPengawasan: [],
    masalah: [],
    chat: [],
    assignedUsers: ['u1', 'u4'],
    createdAt: '2026-01-20T08:00:00',
    updatedAt: '2026-04-22T08:00:00',
  },
]

const ADDITIONAL_SDA_AUDIT_LOGS: AuditLog[] = ADDITIONAL_SDA_PACKAGES.slice(0, 10).map((project, index) => ({
  id: `al-${project.id}`,
  userId: index % 2 === 0 ? 'u3' : 'u6',
  userName: index % 2 === 0 ? 'Siti Rahmawati, ST' : 'Tim Pengawasan B',
  action: index % 3 === 0 ? 'UPDATE_PROYEK' : index % 3 === 1 ? 'UPLOAD_LAPORAN' : 'CREATE_MASALAH',
  entity: 'proyek',
  entityId: project.id,
  detail: `Pembaruan data paket ${project.kode} - ${project.nama}`,
  ip: `192.168.1.${30 + index}`,
  timestamp: `2026-05-${String(24 - index).padStart(2, '0')}T${String(8 + index).padStart(2, '0')}:15:00`,
}))

export const DUMMY_AUDIT_LOGS: AuditLog[] = [
  ...ADDITIONAL_SDA_AUDIT_LOGS,
  {
    id: 'al1',
    userId: 'u3',
    userName: 'Siti Rahmawati, ST',
    action: 'LOGIN',
    entity: 'auth',
    entityId: 'u3',
    detail: 'Login berhasil dari IP 192.168.1.10',
    ip: '192.168.1.10',
    timestamp: '2026-04-26T07:15:00',
  },
  {
    id: 'al2',
    userId: 'u3',
    userName: 'Siti Rahmawati, ST',
    action: 'UPLOAD_LAPORAN',
    entity: 'laporan_harian',
    entityId: 'lh1',
    detail: 'Upload laporan harian + 3 foto untuk proyek PU-DRN-001/2026',
    ip: '192.168.1.10',
    timestamp: '2026-04-26T07:35:00',
  },
  {
    id: 'al3',
    userId: 'u1',
    userName: 'Ir. Ahmad Fauzi, MT',
    action: 'APPROVE_LAPORAN',
    entity: 'laporan_harian',
    entityId: 'lh1',
    detail: 'Menyetujui laporan harian proyek PU-DRN-001/2026',
    ip: '192.168.1.1',
    timestamp: '2026-04-26T09:00:00',
  },
  {
    id: 'al4',
    userId: 'u6',
    userName: 'Tim Pengawasan B',
    action: 'CREATE_CATATAN',
    entity: 'catatan_pengawasan',
    entityId: 'cp1',
    detail: 'Menambah catatan pengawasan untuk proyek PU-DRN-001/2026',
    ip: '192.168.1.20',
    timestamp: '2026-04-26T14:00:00',
  },
]
